Repository ISPP-GRUPO-8/BANQUETBUDDY, pull requests merged in 2024-05, with the labels that each got.

#261 Hotfix/feedback particular
  banquetBuddy/catering_owners/templates/payment/canceled.html
  banquetBuddy/catering_particular/templates/booking_process.html
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/views.py
Labels: bug, Subgroup 1

#283 feat: Improve styles and responsive styles fixed
  banquetBuddy/catering_employees/templates/contact_chat_employee.html
  banquetBuddy/catering_employees/templates/list_work_services.html
  banquetBuddy/catering_owners/templates/contact_chat_owner.html
  banquetBuddy/catering_owners/templates/employee_record.html
  banquetBuddy/catering_owners/templates/list_employee.html
  banquetBuddy/catering_owners/templates/manage_tasks.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_particular/templates/booking_process.html
  banquetBuddy/catering_particular/templates/catering_review.html
  banquetBuddy/catering_particular/templates/contact_chat.html
  banquetBuddy/catering_particular/templates/listar_caterings.html
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/login.html
Labels: enhancement, Subgroup 2, frontend

#281 Test/fix tests
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/catering_particular/tests.py
  requirements.txt
Labels: bug, Subgroup 4

#263 Hotfix/employee feedback#256
  banquetBuddy/catering_employees/templates/employee_offer_list.html
  banquetBuddy/core/templates/core/error_report.html
  banquetBuddy/core/templates/core/error_report_send.html
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/core/templates/core/profile_edit.html
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
Labels: enhancement, Subgroup 2

#284 Test/visual test su1
  banquetBuddy/catering_particular/templates/book_edit.html
  banquetBuddy/catering_particular/templates/my_books.html
  banquetBuddy/catering_particular/test_selenium.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/populate_db.py
Labels: enhancement, Subgroup 1

#293 F-010: Resolver problemas del S3
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/templates/list_my_services.html
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/templates/book_edit.html
  banquetBuddy/catering_particular/templates/listar_caterings.html
  banquetBuddy/catering_particular/test_selenium.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/tests.py
Labels: bug, enhancement, Subgroup 4

#300 Actualización despliegue
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/templates/list_my_services.html
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/templates/book_edit.html
  banquetBuddy/catering_particular/templates/listar_caterings.html
  banquetBuddy/catering_particular/test_selenium.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/subscriptionsplans.html
  banquetBuddy/core/tests.py
  banquetBuddy/core/views.py
Labels: Subgroup 4, deploy

#301 fix: Responsives styles
  banquetBuddy/catering_employees/templates/application_employee_list.html
  banquetBuddy/catering_employees/templates/employee_offer_list.html
  banquetBuddy/catering_employees/templates/my_recommendation_letters.html
  banquetBuddy/catering_owners/templates/applicants_list.html
  banquetBuddy/catering_owners/templates/calendar.html
  banquetBuddy/catering_owners/templates/catering_calendar_home.html
  banquetBuddy/catering_owners/templates/create_catering_service.html
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/templates/list_my_services.html
  banquetBuddy/catering_owners/templates/list_plates.html
  banquetBuddy/catering_owners/templates/manage_tasks.html
  banquetBuddy/catering_owners/templates/offers/create_offer.html
  banquetBuddy/catering_owners/templates/offers/offer_list.html
  banquetBuddy/catering_owners/templates/particular_books.html
  banquetBuddy/catering_owners/templates/recommendation_letter.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_owners/templates/reservations_for_day.html
  banquetBuddy/catering_owners/templates/view_reservation.html
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/templates/booking_process.html
  banquetBuddy/catering_particular/templates/listar_caterings.html
  banquetBuddy/catering_particular/templates/my_books.html
  banquetBuddy/core/templates/core/contact.html
  banquetBuddy/core/templates/core/faq.html
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/login.html
  banquetBuddy/core/templates/core/notifications.html
  banquetBuddy/core/templates/core/previous_policies.html
  banquetBuddy/core/templates/core/previous_terms.html
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/core/templates/core/reset_password.html
  banquetBuddy/static/styles.css
Labels: bug, Subgroup 2, frontend

#308 Fix/minor catering management#306
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/list_employee.html
  banquetBuddy/catering_owners/templates/manage_tasks.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/populate_db.py
Labels: bug, Subgroup 3

#311 fix: Arreglar editar reserva
  banquetBuddy/catering_particular/views.py
Labels: bug, Subgroup 4

#316 Develop
  banquetBuddy/catering_employees/templates/application_employee_list.html
  banquetBuddy/catering_employees/templates/employee_offer_list.html
  banquetBuddy/catering_employees/templates/my_recommendation_letters.html
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/applicants_list.html
  banquetBuddy/catering_owners/templates/calendar.html
  banquetBuddy/catering_owners/templates/catering_calendar_home.html
  banquetBuddy/catering_owners/templates/create_catering_service.html
  banquetBuddy/catering_owners/templates/list_employee.html
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/templates/list_my_services.html
  banquetBuddy/catering_owners/templates/list_plates.html
  banquetBuddy/catering_owners/templates/manage_tasks.html
  banquetBuddy/catering_owners/templates/offers/create_offer.html
  banquetBuddy/catering_owners/templates/offers/offer_list.html
  banquetBuddy/catering_owners/templates/particular_books.html
  banquetBuddy/catering_owners/templates/recommendation_letter.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_owners/templates/reservations_for_day.html
  banquetBuddy/catering_owners/templates/view_reservation.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/templates/book_edit.html
  banquetBuddy/catering_particular/templates/booking_process.html
  banquetBuddy/catering_particular/templates/listar_caterings.html
  banquetBuddy/catering_particular/templates/my_books.html
  banquetBuddy/catering_particular/test_selenium.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/contact.html
  banquetBuddy/core/templates/core/elegir_registro.html
  banquetBuddy/core/templates/core/faq.html
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/login.html
  banquetBuddy/core/templates/core/notifications.html
  banquetBuddy/core/templates/core/previous_policies.html
  banquetBuddy/core/templates/core/previous_terms.html
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/core/templates/core/reset_password.html
  banquetBuddy/core/templates/core/subscriptionsplans.html
  banquetBuddy/core/tests.py
  banquetBuddy/core/views.py
  banquetBuddy/populate_db.py
  banquetBuddy/static/styles.css
  requirements.txt
Labels: enhancement, Subgroup 1, Subgroup 4, Subgroup 2, Subgroup 3

#315 Actualización del despliegue
  banquetBuddy/catering_employees/templates/application_employee_list.html
  banquetBuddy/catering_employees/templates/employee_offer_list.html
  banquetBuddy/catering_employees/templates/my_recommendation_letters.html
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/applicants_list.html
  banquetBuddy/catering_owners/templates/calendar.html
  banquetBuddy/catering_owners/templates/catering_calendar_home.html
  banquetBuddy/catering_owners/templates/create_catering_service.html
  banquetBuddy/catering_owners/templates/list_employee.html
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/templates/list_my_services.html
  banquetBuddy/catering_owners/templates/list_plates.html
  banquetBuddy/catering_owners/templates/manage_tasks.html
  banquetBuddy/catering_owners/templates/offers/create_offer.html
  banquetBuddy/catering_owners/templates/offers/offer_list.html
  banquetBuddy/catering_owners/templates/particular_books.html
  banquetBuddy/catering_owners/templates/recommendation_letter.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_owners/templates/reservations_for_day.html
  banquetBuddy/catering_owners/templates/view_reservation.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/templates/booking_process.html
  banquetBuddy/catering_particular/templates/listar_caterings.html
  banquetBuddy/catering_particular/templates/my_books.html
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/templates/core/contact.html
  banquetBuddy/core/templates/core/elegir_registro.html
  banquetBuddy/core/templates/core/faq.html
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/login.html
  banquetBuddy/core/templates/core/notifications.html
  banquetBuddy/core/templates/core/previous_policies.html
  banquetBuddy/core/templates/core/previous_terms.html
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/core/templates/core/reset_password.html
  banquetBuddy/core/templates/core/subscriptionsplans.html
  banquetBuddy/populate_db.py
  banquetBuddy/static/styles.css
  requirements.txt
Labels: Subgroup 4, deploy
