Repository ISPP-GRUPO-8/BANQUETBUDDY, pull requests merged in 2024-04, with the labels that each got.

#162 Actualización despliegue S2
  banquetBuddy/catering_owners/templates/offers/delete_offer.html
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/templates/core/base.html
Labels: Subgroup 4, deploy

#164 Sprint 2 Changelog
  changelogs/2.0.0/CHANGELOG.md
Labels: documentation, Subgroup 1

#177 Feature/dish management frontend
  .gitignore
  banquetBuddy/catering_owners/templates/add_menu.html
  banquetBuddy/catering_owners/templates/add_plate.html
  banquetBuddy/catering_owners/templates/edit_menu.html
  banquetBuddy/catering_owners/templates/edit_plate.html
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/templates/list_plates.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/static/styles.css
Labels: enhancement, Subgroup 3, frontend

#179 fix: SonarCloud coverage include
  .github/workflows/django.yml
  sonar-project.properties
Labels: bug, enhancement, Subgroup 3

#181 fix: SonarCloud coverage improved
  .github/workflows/django.yml
  sonar-project.properties
Labels: bug, enhancement, Subgroup 3

#187 Fix/186 f 001 refactorizar tests catering employees #186
  banquetBuddy/catering_employees/tests.py
Labels: Subgroup 2

#189 Fix/sonar coverage#178
  .github/workflows/django.yml
  sonar-project.properties
Labels: bug, documentation, enhancement, Subgroup 3

#197 feature: Privacy Policy and Terms improved
  banquetBuddy/core/templates/core/actual_privacy_policy.html
  banquetBuddy/core/templates/core/actual_terms_and_conditions.html
  banquetBuddy/core/templates/core/politicas y terminos anteriores/policyv1_0.html
  banquetBuddy/core/templates/core/politicas y terminos anteriores/termsv1.0.html
  banquetBuddy/core/templates/core/previous_policies.html
  banquetBuddy/core/templates/core/previous_terms.html
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
Labels: documentation, enhancement, Subgroup 3

#195 Feature/client_chat
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/catering_employees/models.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/catering_owners/templates/chat.html
  banquetBuddy/catering_owners/templates/contact_chat_owner.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/models.py
  banquetBuddy/catering_particular/templates/contact_chat.html
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/templates/core/base.html
Labels: enhancement, Subgroup 4

#216 Fix/improve offer and hiring#213
  banquetBuddy/catering_employees/templates/employee_offer_list.html
  banquetBuddy/catering_employees/templatetags/custom_tags.py
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/catering_owners/templates/applicants_list.html
  banquetBuddy/catering_owners/templates/hire_form.html
  banquetBuddy/catering_owners/templates/list_employee.html
  banquetBuddy/catering_owners/templates/offers/create_offer.html
  banquetBuddy/catering_owners/templates/offers/edit_offer.html
  banquetBuddy/catering_owners/templates/offers/offer_list.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/tests.py
  banquetBuddy/populate_db.py
Labels: bug, enhancement, Subgroup 3

#219 Feature/dismiss employee#218
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/catering_owners/templates/edit_employee.html
  banquetBuddy/catering_owners/templates/list_employee.html
  banquetBuddy/catering_owners/templates/offers/create_offer.html
  banquetBuddy/catering_owners/templates/offers/edit_offer.html
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/models.py
  banquetBuddy/core/templates/core/actual_privacy_policy.html
  banquetBuddy/populate_db.py
Labels: Subgroup 3

#223 feature/historial de trabajo para empleados
  banquetBuddy/catering_employees/templates/list_work_services.html
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_employees/urls.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/templates/catering_detail.html
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/permission_checks.py
  banquetBuddy/core/templates/core/base.html
Labels: enhancement, Subgroup 2

#222 Feature/confirmation email
  banquetBuddy/banquetBuddy/urls.py
  banquetBuddy/catering_employees/templates/application_employee_list.html
  banquetBuddy/catering_employees/templates/list_work_services.html
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/templates/chat.html
  banquetBuddy/catering_owners/templates/list_my_services.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/forms.py
  banquetBuddy/catering_particular/templates/catering_contratado.html
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/forms.py
  banquetBuddy/core/templates/core/aboutus.html
  banquetBuddy/core/templates/core/activation_email.html
  banquetBuddy/core/templates/core/activation_invalid.html
  banquetBuddy/core/templates/core/actual_privacy_policy.html
  banquetBuddy/core/templates/core/actual_terms_and_conditions.html
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/contact.html
  banquetBuddy/core/templates/core/elegir_registro.html
  banquetBuddy/core/templates/core/error_report.html
  banquetBuddy/core/templates/core/faq.html
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/login.html
  banquetBuddy/core/templates/core/previous_policies.html
  banquetBuddy/core/templates/core/previous_terms.html
  banquetBuddy/core/templates/core/profile_edit.html
  banquetBuddy/core/templates/core/subscriptionsplans.html
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
Labels: enhancement, Subgroup 4

#232 Feature/task managment#206
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/catering_employees/templates/employee_kanban.html
  banquetBuddy/catering_employees/templates/list_work_services.html
  banquetBuddy/catering_employees/urls.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/catering_owners/templates/manage_tasks.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_owners/templates/task_edit_form.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/static/core/kanban.js
  banquetBuddy/core/static/core/kanban_employee.js
  banquetBuddy/core/templates/core/base.html
Labels: enhancement, Subgroup 3

#234 Actualización despliegue S3
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/catering_employees/templates/employee_kanban.html
  banquetBuddy/catering_employees/templates/list_work_services.html
  banquetBuddy/catering_employees/urls.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/catering_owners/templates/manage_tasks.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_owners/templates/task_edit_form.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/static/core/kanban.js
  banquetBuddy/core/static/core/kanban_employee.js
  banquetBuddy/core/templates/core/base.html
Labels: Subgroup 4, deploy

#230 [Fix] Event Booking
  banquetBuddy/catering_employees/forms.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_particular/templates/book_edit.html
  banquetBuddy/catering_particular/templates/booking_process.html
  banquetBuddy/catering_particular/templates/my_books.html
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/templates/core/base.html
Labels: bug, Subgroup 1

#238 fix: Settings problem solve
  banquetBuddy/banquetBuddy/settings.py
Labels: bug, Subgroup 3

#240 Actualización despliegue S3
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/catering_employees/forms.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/catering_particular/templates/book_edit.html
  banquetBuddy/catering_particular/templates/booking_process.html
  banquetBuddy/catering_particular/templates/my_books.html
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/templates/core/base.html
Labels: Subgroup 4, deploy

#243 doc: Add Sprint 3 commit changelog
  changelogs/3.0.0/CHANGELOG.md
Labels: documentation, Subgroup 1

#258 Feature/improve populate#251
  banquetBuddy/catering_employees/templates/employee_offer_list.html
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/templates/list_employee.html
  banquetBuddy/catering_owners/templates/manage_tasks.html
  banquetBuddy/catering_owners/templates/offers/offer_list.html
  banquetBuddy/populate/catering_companies.json
  banquetBuddy/populate/catering_services.json
  banquetBuddy/populate/employee_work_services.json
  banquetBuddy/populate/employees.json
  banquetBuddy/populate/events.json
  banquetBuddy/populate/job_applications.json
  banquetBuddy/populate/menus.json
  banquetBuddy/populate/messages.json
  banquetBuddy/populate/offers.json
  banquetBuddy/populate/particulars.json
  banquetBuddy/populate/plates.json
  banquetBuddy/populate/recommendationLetter.json
  banquetBuddy/populate/review.json
  banquetBuddy/populate/tasks.json
  banquetBuddy/populate_db.py
Labels: enhancement, Subgroup 3

#254 fix: Fix edit offer not showing events
  banquetBuddy/catering_owners/views.py
Labels: bug, Subgroup 2
