Repository ISPP-GRUPO-8/BANQUETBUDDY, pull requests merged in 2024-03, with the labels that each got.

#25 fix: home page buttons visualization
  banquetBuddy/core/templates/core/home.html
Labels: bug, Subgroup 1, frontend

#27 feat: login
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/core/backends.py
  banquetBuddy/core/forms.py
  banquetBuddy/core/models.py
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/login.html
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
  banquetBuddy/populate_db.py
Labels: enhancement, Subgroup 1

#36 feat: User logout
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/tests.py
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
Labels: enhancement, Subgroup 1

#39 test: Add login tests
  banquetBuddy/core/tests.py
  requirements.txt
Labels: Subgroup 1

#38 feat: Edit user profile
  banquetBuddy/core/admin.py
  banquetBuddy/core/migrations/0001_initial.py
  banquetBuddy/core/static/core/styles.css
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/core/templates/core/profile_edit.html
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
Labels: enhancement, Subgroup 4

#60 fix: Improved management of menus, plates, and cuisine types
  banquetBuddy/clear_database.py
  banquetBuddy/core/migrations/0001_initial.py
  banquetBuddy/core/models.py
  banquetBuddy/populate_db.py
Labels: Subgroup 3

#65 Feature/GitHub pro
  README.md
Labels: documentation, Subgroup 4

#71 Feature/caterings search
  banquetBuddy/catering_particular/templates/listar_caterings.html
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
Labels: enhancement, Subgroup 4

#74 fix: Update event-menu relationship and simplify models
  banquetBuddy/core/admin.py
  banquetBuddy/core/migrations/0001_initial.py
  banquetBuddy/core/models.py
  banquetBuddy/populate_db.py
  banquetBuddy/static/images/plates/plate1.JPG
  banquetBuddy/static/images/plates/plate2.JPG
  banquetBuddy/static/images/plates/plate3.JPG
  banquetBuddy/static/images/plates/plate4.JPG
  banquetBuddy/static/images/plates/plate5.JPG
  banquetBuddy/static/images/plates/plate6.JPG
Labels: enhancement, Subgroup 3

#82 Feature/company update
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/profile_company_edit.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/migrations/0001_initial.py
  banquetBuddy/core/views.py
Labels: enhancement, Subgroup 3

#89 Feature/menu managment
  banquetBuddy/catering_owners/admin.py
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/catering_owners/templates/add_menu.html
  banquetBuddy/catering_owners/templates/edit_menu.html
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/clean_django_modules.py
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/delete_all_tables_database.py
  banquetBuddy/populate_db.py
Labels: enhancement, Subgroup 3

#94 Feature/menu management frontend
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/add_menu.html
  banquetBuddy/catering_owners/templates/edit_menu.html
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/views.py
Labels: Subgroup 3, frontend

#97 feature/company_profile
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/profile_company_edit.html
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/forms.py
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/core/views.py
Labels: Subgroup 3, frontend

#100 Fix/arreglar fallos integracion
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_owners/templates/error_catering.html
  banquetBuddy/catering_owners/templates/offers/offer_list.html
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/templates/core/base.html
Labels: bug, Subgroup 2

#93 Feature/Caterings by location
  banquetBuddy/catering_particular/templates/listar_caterings.html
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
Labels: enhancement, Subgroup 4

#102 Feature/catalog search home
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/tests.py
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
Labels: enhancement, Subgroup 4

#81 Feature/catering review
  banquetBuddy/catering_particular/templates/catering_detail.html
  banquetBuddy/catering_particular/templates/catering_review.html
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/migrations/0001_initial.py
  banquetBuddy/logos_catering/cateringbenito.png
  banquetBuddy/logos_catering/cocinaantonio.jpg
  banquetBuddy/logos_catering/fusiongourmet.png
  banquetBuddy/logos_catering/lamediterranea.jpg
  banquetBuddy/logos_catering/rinconmexicano.jpg
  banquetBuddy/logos_catering/sabororiental.jpg
  banquetBuddy/media/cateringbenito_UKcijKL.png
  banquetBuddy/media/cateringbenito_y5Id88q.png
  banquetBuddy/media/cocinaantonio_1xGsBAy.jpg
  banquetBuddy/media/cocinaantonio_EweY4KF.jpg
  banquetBuddy/media/fusiongourmet_P3HTZe3.png
  banquetBuddy/media/fusiongourmet_oHZJfR2.png
  banquetBuddy/media/lamediterranea_fH2EHU1.jpg
  banquetBuddy/media/lamediterranea_wygQJwk.jpg
  banquetBuddy/media/rinconmexicano_8ihzcwo.jpg
  banquetBuddy/media/rinconmexicano_LrnmFu4.jpg
  banquetBuddy/media/sabororiental_qYiyNQM.jpg
  banquetBuddy/media/sabororiental_s1jkvP9.jpg
Labels: enhancement, Subgroup 1

#108 Feature/upload curriculum
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/banquetBuddy/urls.py
  banquetBuddy/catering_employees/forms.py
  banquetBuddy/catering_employees/models.py
  banquetBuddy/catering_employees/templates/employee_offer_list.html
  banquetBuddy/catering_employees/templates/error_employee_curriculum.html
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/templates/applicants_list.html
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/middleware.py
  banquetBuddy/core/templates/core/home.html
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/core/templates/core/profile_edit.html
  banquetBuddy/core/templates/core/registro_empleado.html
  banquetBuddy/core/views.py
  banquetBuddy/media/cateringbenito_UKcijKL.png
  banquetBuddy/media/cateringbenito_y5Id88q.png
  banquetBuddy/media/cocinaantonio_1xGsBAy.jpg
  banquetBuddy/media/cocinaantonio_EweY4KF.jpg
  banquetBuddy/media/fusiongourmet_P3HTZe3.png
  banquetBuddy/media/fusiongourmet_oHZJfR2.png
  banquetBuddy/media/lamediterranea_fH2EHU1.jpg
  banquetBuddy/media/lamediterranea_wygQJwk.jpg
  banquetBuddy/media/rinconmexicano_8ihzcwo.jpg
  banquetBuddy/media/rinconmexicano_LrnmFu4.jpg
  banquetBuddy/media/sabororiental_qYiyNQM.jpg
  banquetBuddy/media/sabororiental_s1jkvP9.jpg
Labels: enhancement, Subgroup 2

#107 fix: All test corrected
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/tests.py
Labels: bug, Subgroup 1

#104 Feature/error report
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/core/forms.py
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/error_report.html
  banquetBuddy/core/tests.py
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
  banquetBuddy/media/cateringbenito_UKcijKL.png
  banquetBuddy/media/cateringbenito_y5Id88q.png
  banquetBuddy/media/cocinaantonio_1xGsBAy.jpg
  banquetBuddy/media/cocinaantonio_EweY4KF.jpg
  banquetBuddy/media/fusiongourmet_P3HTZe3.png
  banquetBuddy/media/fusiongourmet_oHZJfR2.png
  banquetBuddy/media/lamediterranea_fH2EHU1.jpg
  banquetBuddy/media/lamediterranea_wygQJwk.jpg
  banquetBuddy/media/rinconmexicano_8ihzcwo.jpg
  banquetBuddy/media/rinconmexicano_LrnmFu4.jpg
  banquetBuddy/media/sabororiental_qYiyNQM.jpg
  banquetBuddy/media/sabororiental_s1jkvP9.jpg
Labels: enhancement, Subgroup 1

#121 feat: Add Privacy Policy and Terms and Conditions
  banquetBuddy/catering_owners/templates/registro_company.html
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/privacy_policy.html
  banquetBuddy/core/templates/core/registro_empleado.html
  banquetBuddy/core/templates/core/registro_particular.html
  banquetBuddy/core/templates/core/terms_and_conditions.html
  banquetBuddy/core/urls.py
  banquetBuddy/core/views.py
Labels: documentation, enhancement, Subgroup 3

#120 Feature/booking management
  banquetBuddy/catering_employees/templates/error_employee_curriculum.html
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/calendar.html
  banquetBuddy/catering_owners/templates/catering_calendar_home.html
  banquetBuddy/catering_owners/templates/list_menus.html
  banquetBuddy/catering_owners/templates/offers/aplpy_offer.html
  banquetBuddy/catering_owners/templates/offers/base.html
  banquetBuddy/catering_owners/templates/offers/create_offer.html
  banquetBuddy/catering_owners/templates/offers/delete_offer.html
  banquetBuddy/catering_owners/templates/offers/edit_offer.html
  banquetBuddy/catering_owners/templates/offers/offer_list.html
  banquetBuddy/catering_owners/templates/reservations.html
  banquetBuddy/catering_owners/templates/reservations_for_day.html
  banquetBuddy/catering_owners/templates/view_reservation.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/templates/core/base.html
  banquetBuddy/core/templates/core/notifications.html
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/logos_catering/cateringbenito.png
  banquetBuddy/logos_catering/cateringbenito_Ef6hBDz.png
  banquetBuddy/logos_catering/cocinaantonio.jpg
  banquetBuddy/logos_catering/cocinaantonio_a0uC1ag.jpg
  banquetBuddy/logos_catering/fusiongourmet.png
  banquetBuddy/logos_catering/fusiongourmet_75pwWPd.png
  banquetBuddy/logos_catering/lamediterranea.jpg
  banquetBuddy/logos_catering/lamediterranea_wkIMYXk.jpg
  banquetBuddy/logos_catering/rinconmexicano.jpg
  banquetBuddy/logos_catering/rinconmexicano_gY6v0gE.jpg
  banquetBuddy/logos_catering/sabororiental.jpg
  banquetBuddy/logos_catering/sabororiental_AQJpGH1.jpg
Labels: enhancement, Subgroup 3

#72 Feature/hired catering
  banquetBuddy/banquetBuddy/settings.py
  banquetBuddy/catering_particular/templates/catering_contratado.html
  banquetBuddy/catering_particular/urls.py
  banquetBuddy/catering_particular/views.py
  banquetBuddy/core/templates/core/base.html
Labels: enhancement, Subgroup 4

#122 fix: All test fixed
  banquetBuddy/catering_particular/tests.py
  banquetBuddy/catering_particular/views.py
Labels: bug, Subgroup 1

#106 Feature/Django workflow
  .github/workflows/django.yml
  banquetBuddy/catering_particular/tests.py
Labels: Subgroup 1

#127 Feature/Add recommendation letter model
  banquetBuddy/catering_employees/models.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/core/models.py
  banquetBuddy/populate_db.py
Labels: enhancement, Subgroup 1

#125 Feature/crud catering services
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/create_catering_service.html
  banquetBuddy/catering_owners/templates/delete_service.html
  banquetBuddy/catering_owners/templates/edit_catering_service.html
  banquetBuddy/catering_owners/templates/list_my_services.html
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/templates/core/base.html
Labels: enhancement, Subgroup 4

#135 feat: Implement Plate Management
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/catering_owners/templates/add_plate.html
  banquetBuddy/catering_owners/templates/edit_plate.html
  banquetBuddy/catering_owners/templates/list_plates.html
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/populate_db.py
Labels: enhancement, Subgroup 3

#137 Feature/recommendation letter
  banquetBuddy/catering_employees/templates/my_recommendation_letters.html
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_employees/urls.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/models.py
  banquetBuddy/catering_owners/templates/list_employee.html
  banquetBuddy/catering_owners/templates/list_my_services.html
  banquetBuddy/catering_owners/templates/recommendation_letter.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/populate_db.py
Labels: enhancement, Subgroup 1

#147 Feature/access restriction
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/templates/core/subscriptionsplans.html
  banquetBuddy/core/views.py
Labels: enhancement, Subgroup 3

#149 Feature/change of plan
  banquetBuddy/catering_owners/forms.py
  banquetBuddy/catering_owners/templates/profile_company_edit.html
  banquetBuddy/catering_owners/urls.py
  banquetBuddy/catering_owners/views.py
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/core/templates/core/subscriptionsplans.html
Labels: enhancement, Subgroup 3

#157 Feature/setup sonarcloud#148
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: enhancement, Subgroup 3

#155 feat: Changelogs automation
  .github/workflows/changelog.yml
  changelogs/1.0.0/CHANGELOG.md
  requirements.txt
Labels: enhancement, Subgroup 1

#158 fix: Catering employees functionalities
  banquetBuddy/catering_employees/templates/application_employee_list.html
  banquetBuddy/catering_employees/tests.py
  banquetBuddy/catering_employees/views.py
  banquetBuddy/catering_owners/templates/applicants_list.html
  banquetBuddy/catering_owners/tests.py
  banquetBuddy/core/templates/core/profile.html
  banquetBuddy/media/curriculums/curriculum.pdf
  banquetBuddy/populate_db.py
Labels: bug, Subgroup 2

#161 Hotfix/141 hotfix arreglar url hacking apartado de gestin de ofertas
  banquetBuddy/catering_owners/templates/offers/delete_offer.html
  banquetBuddy/catering_owners/views.py
Labels: bug
